version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: backend/docker/golang/Dockerfile
    container_name: backend
    tty: true
    working_dir: /go/src/app
    depends_on:
      - db
    environment:
      - FIREBASE_CREDENTIALS_FILE=backend/config/firebase_credentials.json

    volumes:
      - ./backend:/go/src/app
      - ${FIREBASE_CREDENTIALS_FILE}:/go/src/app/config/firebase_credentials.json
    ports:
      - "8000:8000"

  db:
    build:
      context: .
      dockerfile: backend/docker/postgres/Dockerfile
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-golang_nextjs}

volumes:
  pgdata:
