// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Golang Next.js API
//
//	This is a sample API
//	Schemes:
//	  http
//	Host: localhost:5000
//	BasePath: /v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
