// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a sample API",
    "title": "Golang Next.js API",
    "version": "1.0.0"
  },
  "host": "localhost:5000",
  "basePath": "/v1",
  "paths": {
    "/task": {
      "post": {
        "description": "This endpoint creates a new task with the given title and content.",
        "summary": "Create a new task",
        "parameters": [
          {
            "type": "string",
            "description": "The title of the task.",
            "name": "title",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "The content of the task.",
            "name": "content",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "Task created successfully.",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Task created successfully."
                },
                "task": {
                  "type": "object",
                  "properties": {
                    "content": {
                      "type": "string"
                    },
                    "id": {
                      "type": "integer",
                      "format": "int64"
                    },
                    "title": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid input, please provide the required parameters.",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Invalid input, please provide the required parameters."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Internal server error."
                }
              }
            }
          }
        }
      }
    },
    "/tasks": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Get a list of tasks",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Task"
              }
            }
          }
        }
      }
    },
    "/tasks/{id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Get a task by ID",
        "parameters": [
          {
            "type": "string",
            "description": "ID of the task to get",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Task"
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Get a list of users",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/User"
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Get a user by ID",
        "parameters": [
          {
            "type": "string",
            "description": "ID of the user to get",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Task": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "created_by": {
          "type": "string"
        },
        "done": {
          "type": "boolean"
        },
        "id": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "age": {
          "type": "integer"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "email": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a sample API",
    "title": "Golang Next.js API",
    "version": "1.0.0"
  },
  "host": "localhost:5000",
  "basePath": "/v1",
  "paths": {
    "/task": {
      "post": {
        "description": "This endpoint creates a new task with the given title and content.",
        "summary": "Create a new task",
        "parameters": [
          {
            "type": "string",
            "description": "The title of the task.",
            "name": "title",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "The content of the task.",
            "name": "content",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "Task created successfully.",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Task created successfully."
                },
                "task": {
                  "type": "object",
                  "properties": {
                    "content": {
                      "type": "string"
                    },
                    "id": {
                      "type": "integer",
                      "format": "int64"
                    },
                    "title": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid input, please provide the required parameters.",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Invalid input, please provide the required parameters."
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Internal server error."
                }
              }
            }
          }
        }
      }
    },
    "/tasks": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Get a list of tasks",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Task"
              }
            }
          }
        }
      }
    },
    "/tasks/{id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Get a task by ID",
        "parameters": [
          {
            "type": "string",
            "description": "ID of the task to get",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Task"
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Get a list of users",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/User"
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Get a user by ID",
        "parameters": [
          {
            "type": "string",
            "description": "ID of the user to get",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "PostTaskCreatedBodyTask": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Task": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "created_by": {
          "type": "string"
        },
        "done": {
          "type": "boolean"
        },
        "id": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "age": {
          "type": "integer"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "email": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    }
  }
}`))
}
