import { useEffect, useState } from "react";
import Head from "next/head";
import { apiClient } from "@/libs/api-client";

export default function Home() {
  const [users, setUsers] = useState([]);
  const fetchUsers = async () => {
    const res = await apiClient.get("/tasks");
    console.log(res.data);
    setUsers(res.data);
  };

  useEffect(() => {
    fetchUsers();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>fff</div>
      </main>
    </>
  );
}
