// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteTasksIDOKCode is the HTTP code returned for type DeleteTasksIDOK
const DeleteTasksIDOKCode int = 200

/*
DeleteTasksIDOK Task deleted successfully

swagger:response deleteTasksIdOK
*/
type DeleteTasksIDOK struct {
}

// NewDeleteTasksIDOK creates DeleteTasksIDOK with default headers values
func NewDeleteTasksIDOK() *DeleteTasksIDOK {

	return &DeleteTasksIDOK{}
}

// WriteResponse to the client
func (o *DeleteTasksIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteTasksIDBadRequestCode is the HTTP code returned for type DeleteTasksIDBadRequest
const DeleteTasksIDBadRequestCode int = 400

/*
DeleteTasksIDBadRequest Invalid input, ID must be a valid string

swagger:response deleteTasksIdBadRequest
*/
type DeleteTasksIDBadRequest struct {
}

// NewDeleteTasksIDBadRequest creates DeleteTasksIDBadRequest with default headers values
func NewDeleteTasksIDBadRequest() *DeleteTasksIDBadRequest {

	return &DeleteTasksIDBadRequest{}
}

// WriteResponse to the client
func (o *DeleteTasksIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteTasksIDNotFoundCode is the HTTP code returned for type DeleteTasksIDNotFound
const DeleteTasksIDNotFoundCode int = 404

/*
DeleteTasksIDNotFound Task not found

swagger:response deleteTasksIdNotFound
*/
type DeleteTasksIDNotFound struct {
}

// NewDeleteTasksIDNotFound creates DeleteTasksIDNotFound with default headers values
func NewDeleteTasksIDNotFound() *DeleteTasksIDNotFound {

	return &DeleteTasksIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteTasksIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteTasksIDInternalServerErrorCode is the HTTP code returned for type DeleteTasksIDInternalServerError
const DeleteTasksIDInternalServerErrorCode int = 500

/*
DeleteTasksIDInternalServerError Internal server error

swagger:response deleteTasksIdInternalServerError
*/
type DeleteTasksIDInternalServerError struct {
}

// NewDeleteTasksIDInternalServerError creates DeleteTasksIDInternalServerError with default headers values
func NewDeleteTasksIDInternalServerError() *DeleteTasksIDInternalServerError {

	return &DeleteTasksIDInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteTasksIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
