// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"golang-nextjs-app/restapi/models"
)

// GetTasksIDOKCode is the HTTP code returned for type GetTasksIDOK
const GetTasksIDOKCode int = 200

/*
GetTasksIDOK OK

swagger:response getTasksIdOK
*/
type GetTasksIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Task `json:"body,omitempty"`
}

// NewGetTasksIDOK creates GetTasksIDOK with default headers values
func NewGetTasksIDOK() *GetTasksIDOK {

	return &GetTasksIDOK{}
}

// WithPayload adds the payload to the get tasks Id o k response
func (o *GetTasksIDOK) WithPayload(payload *models.Task) *GetTasksIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tasks Id o k response
func (o *GetTasksIDOK) SetPayload(payload *models.Task) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTasksIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTasksIDBadRequestCode is the HTTP code returned for type GetTasksIDBadRequest
const GetTasksIDBadRequestCode int = 400

/*
GetTasksIDBadRequest Invalid input, ID must be a valid integer

swagger:response getTasksIdBadRequest
*/
type GetTasksIDBadRequest struct {
}

// NewGetTasksIDBadRequest creates GetTasksIDBadRequest with default headers values
func NewGetTasksIDBadRequest() *GetTasksIDBadRequest {

	return &GetTasksIDBadRequest{}
}

// WriteResponse to the client
func (o *GetTasksIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetTasksIDNotFoundCode is the HTTP code returned for type GetTasksIDNotFound
const GetTasksIDNotFoundCode int = 404

/*
GetTasksIDNotFound Task not found

swagger:response getTasksIdNotFound
*/
type GetTasksIDNotFound struct {
}

// NewGetTasksIDNotFound creates GetTasksIDNotFound with default headers values
func NewGetTasksIDNotFound() *GetTasksIDNotFound {

	return &GetTasksIDNotFound{}
}

// WriteResponse to the client
func (o *GetTasksIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetTasksIDInternalServerErrorCode is the HTTP code returned for type GetTasksIDInternalServerError
const GetTasksIDInternalServerErrorCode int = 500

/*
GetTasksIDInternalServerError Internal server error

swagger:response getTasksIdInternalServerError
*/
type GetTasksIDInternalServerError struct {
}

// NewGetTasksIDInternalServerError creates GetTasksIDInternalServerError with default headers values
func NewGetTasksIDInternalServerError() *GetTasksIDInternalServerError {

	return &GetTasksIDInternalServerError{}
}

// WriteResponse to the client
func (o *GetTasksIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
