// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Takenari-Yamamoto/golang-nextjs-app/restapi/models"
)

// PostUsersOKCode is the HTTP code returned for type PostUsersOK
const PostUsersOKCode int = 200

/*
PostUsersOK OK

swagger:response postUsersOK
*/
type PostUsersOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPostUsersOK creates PostUsersOK with default headers values
func NewPostUsersOK() *PostUsersOK {

	return &PostUsersOK{}
}

// WithPayload adds the payload to the post users o k response
func (o *PostUsersOK) WithPayload(payload *models.User) *PostUsersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users o k response
func (o *PostUsersOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
