// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostTaskCreatedCode is the HTTP code returned for type PostTaskCreated
const PostTaskCreatedCode int = 201

/*
PostTaskCreated Task created successfully.

swagger:response postTaskCreated
*/
type PostTaskCreated struct {

	/*
	  In: Body
	*/
	Payload *PostTaskCreatedBody `json:"body,omitempty"`
}

// NewPostTaskCreated creates PostTaskCreated with default headers values
func NewPostTaskCreated() *PostTaskCreated {

	return &PostTaskCreated{}
}

// WithPayload adds the payload to the post task created response
func (o *PostTaskCreated) WithPayload(payload *PostTaskCreatedBody) *PostTaskCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post task created response
func (o *PostTaskCreated) SetPayload(payload *PostTaskCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTaskCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostTaskBadRequestCode is the HTTP code returned for type PostTaskBadRequest
const PostTaskBadRequestCode int = 400

/*
PostTaskBadRequest Invalid input, please provide the required parameters.

swagger:response postTaskBadRequest
*/
type PostTaskBadRequest struct {

	/*
	  In: Body
	*/
	Payload *PostTaskBadRequestBody `json:"body,omitempty"`
}

// NewPostTaskBadRequest creates PostTaskBadRequest with default headers values
func NewPostTaskBadRequest() *PostTaskBadRequest {

	return &PostTaskBadRequest{}
}

// WithPayload adds the payload to the post task bad request response
func (o *PostTaskBadRequest) WithPayload(payload *PostTaskBadRequestBody) *PostTaskBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post task bad request response
func (o *PostTaskBadRequest) SetPayload(payload *PostTaskBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTaskBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostTaskInternalServerErrorCode is the HTTP code returned for type PostTaskInternalServerError
const PostTaskInternalServerErrorCode int = 500

/*
PostTaskInternalServerError Internal server error.

swagger:response postTaskInternalServerError
*/
type PostTaskInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *PostTaskInternalServerErrorBody `json:"body,omitempty"`
}

// NewPostTaskInternalServerError creates PostTaskInternalServerError with default headers values
func NewPostTaskInternalServerError() *PostTaskInternalServerError {

	return &PostTaskInternalServerError{}
}

// WithPayload adds the payload to the post task internal server error response
func (o *PostTaskInternalServerError) WithPayload(payload *PostTaskInternalServerErrorBody) *PostTaskInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post task internal server error response
func (o *PostTaskInternalServerError) SetPayload(payload *PostTaskInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTaskInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
