// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Takenari-Yamamoto/golang-nextjs-app/restapi/models"
)

// PutUsersIDOKCode is the HTTP code returned for type PutUsersIDOK
const PutUsersIDOKCode int = 200

/*
PutUsersIDOK OK

swagger:response putUsersIdOK
*/
type PutUsersIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPutUsersIDOK creates PutUsersIDOK with default headers values
func NewPutUsersIDOK() *PutUsersIDOK {

	return &PutUsersIDOK{}
}

// WithPayload adds the payload to the put users Id o k response
func (o *PutUsersIDOK) WithPayload(payload *models.User) *PutUsersIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put users Id o k response
func (o *PutUsersIDOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUsersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
